/**
 * **AUTHORED FROM SPEC TEXT ONLY** (`24 §3` step 2, `20 §4.3` separation rule). Sources read:
 * `specs/22-operations-recovery.md` (`22-F16`, `22-N3`, `22 §7`, `22 §5`),
 * `plans/saas-pivot/plan-of-record.md` §0 (R21, R35, R38, R40),
 * `specs/01-kernel-sync.md` (`01-F1`, `01-F4`, `01-F62`, `01-F71`),
 * `specs/28-tenancy.md` (`28-F1`, `28-F5`, `28-F10`, `28-F14`, `28-F18`, `28-F20`),
 * `specs/14-backoffice.md` (`14-F30`, `14-F39` — the FR-decided-action precedent),
 * `specs/18-engineering-handbook.md` §§5/6, and the landed precedent
 * `services/api/src/__acceptance__/tenant-isolation.test.ts`. **No implementation of an export
 * trigger exists at authoring time and this session wrote none.**
 *
 * ═══ WHAT R38 PUTS ON THIS PLANE ══════════════════════════════════════════════════════════════
 *
 * R38: *"NIGHTLY PER-TENANT BACKUP + A RESTORE THAT HAS ACTUALLY BEEN RUN + **OWNER-TRIGGERED
 * EXPORT**."* `22-F16` says where the trigger lives and who may pull it: *"**Owner-triggered** full
 * export from back office (doc 14) … generated async by a job, delivered as a bundle … (audited;
 * **owner-role only**)"*.
 *
 * So this plane owns two things and only two: **who may ask**, and **which tenant the answer is
 * about**. The BUNDLE — its contents, its completeness, its format — is generated by
 * `services/jobs` and is asserted in
 * `services/jobs/src/__acceptance__/tenant-backup-restore.test.ts` §G, by a suite that can read
 * the kernel database. ⚠ **The seam between the two halves is OWED and is named here rather than
 * assumed**: nothing in this file proves that pulling the trigger causes the job to run. That is
 * this wave's recurring defect in its purest form and it must be closed with a hand-written
 * assertion by whoever wires the queue — a passing suite on either side proves nothing about it.
 *
 * ═══ WHY THIS FILE IS AN ISOLATION SUITE (R35's ISOLATION TIER) ═══════════════════════════════
 *
 * `01-F71` is the register, and its rule is not advisory:
 *
 *   > *"Each point carries a test that FAILS when that point alone is removed. Reading is not
 *   > evidence and neither is a green suite: **a suite exercising one tenant passes with all four
 *   > deleted.** The test must run two tenants and mutate the point under test."*
 *   > … *"**Adding an enforcement point adds a clause here** — the list is the register, and an
 *   > unlisted check is one no test is aimed at."*
 *
 * An export path is a new enforcement point: it is the one surface in the product whose entire
 * purpose is to hand a tenant a copy of a tenant's data. So this file runs **two fully populated
 * tenants on ONE host with ONE set of stores**, and every leak assertion is paired with a control
 * proving the datum was genuinely present and genuinely reachable by the tenant entitled to it —
 * `01-F71`'s own measured lesson from the reference-serve round: *"a fixture that cannot express a
 * foreign key cannot test a refusal of one"*, and *"refused and served nothing are separate
 * claims"*.
 *
 * **OWED, and it is a spec change rather than code:** a clause in `01-F71` naming this point, on
 * that FR's own rule. `28-F18` already records three cross-tenant paths owed clauses; this is a
 * fourth enforcement point and the register is where it goes.
 *
 * ═══ ORACLE-PINNED SURFACE — BINDING FOR THE IMPLEMENTING SESSION ═════════════════════════════
 *
 *   1. **`ApiServerOptions` gains `exports?: ExportRequests`** — optional here for the reason every
 *      other port is (`catalog`, `devices`, `ledger`, `tenancy`, `users`: suites that predate it
 *      still have to boot) and **REQUIRED once resolved**. Its fallback must **REFUSE every call**,
 *      never a memory stub: AGENTS.md measured that *"Rule B asks whether an optional member is
 *      supplied, never whether what was supplied is real, and a stub is a supply"*, and on this
 *      surface a stub means an owner told her export is being prepared when nothing is preparing
 *      it — under `22-N3`, which requires her to see *"progress state, never a spinner"*.
 *
 *   2. **Two procedures under a `governance` namespace**, both gated by `authorized(...)`:
 *        - `governance.requestExport` — MUTATION, input `{}`. **Takes no org.** Returns
 *          `{ export_id, state }`.
 *        - `governance.exportStatus` — QUERY, input `{ export_id }`. Returns the record, for the
 *          CALLER'S org only.
 *
 *   3. **The port**, hand-copied here rather than imported because the module does not exist yet
 *      (a broken import is not a legitimate red; a rename turns this suite red, which is the safe
 *      direction):
 *
 *        type ExportRequestRecord = {
 *          export_id: string; org_id: string; requested_by_user_id: string;
 *          requested_at: number; state: "queued" | "running" | "ready" | "failed";
 *          bundle: string | null;
 *        };
 *        type ExportRequests = {
 *          request(input: { org_id; requested_by_user_id; requested_at }): Promise<Record>;
 *          get(org_id: string, export_id: string): Promise<Record | null>;
 *          list(org_id: string): Promise<readonly Record[]>;
 *        };
 *
 *      The port takes `org_id` as its first argument on both reads, exactly as
 *      `where org_id = $1` does — and the fixture below is deliberately **undefended**, answering
 *      whatever org it is asked about without complaint. A store that refused a foreign org would
 *      make the STORE the enforcement point and hide whether the SERVICE has one.
 *
 *   4. **⚠ THE PERMISSION ACTION IS NOT PINNED BY THIS SUITE, AND THAT IS A FINDING RATHER THAN A
 *      GAP IN THE ORACLE.** `authorized()` takes its action from `PERMISSION_ACTIONS`, a closed
 *      `as const` list in `packages/domain/src/permissions.ts`, and `assertEveryProcedureIsGated`
 *      refuses at boot to host a procedure naming none. Measured 2026-08-20, that list has **no
 *      export, governance or backup action** — so `22-F16`'s owner-triggered export **cannot be
 *      built or booted** until an action exists, exactly as `14-F14` could not before `14-F39`
 *      declared `user.manage`. The precedent for where it is decided is settled and unanimous:
 *      `device.manage` (`14-F30`), `user.manage` (`14-F39`), `availability.toggle` (`02-F46`) and
 *      `customer.record` (`02-F47`) are each FR-decided in the doc that owns the surface, because
 *      Appendix A has no row for any of them. **This oracle therefore asserts the OUTCOME and
 *      never the string**: an owner is served, a cashier and a branch manager are refused as an
 *      authorization decision. Whatever the action is called, those three facts are `22-F16`'s.
 *
 * ═══ WHAT THIS SUITE DELIBERATELY DOES NOT ASSERT, WITH THE MEASUREMENT ═══════════════════════
 *
 *   - **`governance.export_generated`** (`22-F16`'s audit record). `packages/domain` declares no
 *     `governance.*` payload schema at all — measured 2026-08-20 — so `01-F4` refuses the emit, and
 *     `01-F62` closes the org-scoped set at five types that do not include it while a branch-scoped
 *     envelope needs a **device** to stamp it. `28-F10` and `28-F14` already file this as owed:
 *     *"doc 22's to declare, doc 01's to absorb"*. **So an export is unaudited today** — the owner
 *     pulls a lever that copies her entire ledger and the ledger records nothing about it.
 *     Asserting the emit would leave a test permanently red under a correct implementation, which
 *     this repo rates as damaging as a vacuous one.
 *   - **`22 §7`'s layer-2 "who may trigger export"**. It is configurable *within* platform bounds
 *     with an owner default, and no layer-2 config plane exists (`28-F20` (iii)). This asserts the
 *     default `22-F16` states as a rule — *owner-role only* — and a later config surface narrows or
 *     widens it in one place.
 *   - **`22-N3`'s time budgets** (< 1 h for a one-branch org). A timing assertion is `24-F12`
 *     flakiness on a fixture with four events. What IS asserted from `22-N3` is its other half: the
 *     owner sees a **state**, from a closed set, rather than a spinner.
 */

import { hashPin } from "@restos/domain";
import superjson from "superjson";
import { beforeAll, describe, expect, it } from "vitest";
import { createApiServer } from "../server.js";
import { createMemoryUserStore, type UserRecord } from "../users.js";

// ════════════════════════════════════════════════════════════════════════════════════════════════
// THE PINNED PORT (see the header, item 3)
// ════════════════════════════════════════════════════════════════════════════════════════════════

type ExportState = "queued" | "running" | "ready" | "failed";
const EXPORT_STATES: readonly ExportState[] = ["queued", "running", "ready", "failed"];

type ExportRequestRecord = {
  export_id: string;
  org_id: string;
  requested_by_user_id: string;
  requested_at: number;
  state: ExportState;
  bundle: string | null;
};

type ExportRequests = {
  request(input: {
    org_id: string;
    requested_by_user_id: string;
    requested_at: number;
  }): Promise<ExportRequestRecord>;
  get(org_id: string, export_id: string): Promise<ExportRequestRecord | null>;
  list(org_id: string): Promise<readonly ExportRequestRecord[]>;
};

// ════════════════════════════════════════════════════════════════════════════════════════════════
// TWO TENANTS
// ════════════════════════════════════════════════════════════════════════════════════════════════

const ORG_A = "org-kababjees";
const A_BRANCH = "branch-gulberg";
const ORG_B = "org-student-biryani";
const B_BRANCH = "branch-nazimabad";

const SECRET = "r38-owner-export-session-secret-not-a-real-one";
const PASSWORD = "correct horse battery staple";
const T0 = 1_786_039_200_000;

const A_OWNER = "user-a-owner";
const A_MANAGER = "user-a-manager";
const A_CASHIER = "user-a-cashier";
const B_OWNER = "user-b-owner";

const A_OWNER_EMAIL = "owner@kababjees.test";
const A_MANAGER_EMAIL = "manager@kababjees.test";
const A_CASHIER_EMAIL = "cashier@kababjees.test";
const B_OWNER_EMAIL = "owner@student-biryani.test";

/** A bundle reference that exists in exactly one tenant. `§0` proves it. */
const B_BUNDLE = "bundle-student-biryani-2026-08-20.tar";
const A_BUNDLE = "bundle-kababjees-2026-08-20.tar";

/**
 * The store. **Deliberately undefended** — it answers exactly the org it is asked about, the way
 * `where org_id = $1` does, and it never validates that the org it was handed is the org the
 * caller is entitled to. That check is the SERVICE's, and a store that performed it would mask
 * the absence of the service's own (`tenant-isolation.test.ts`'s rule 1).
 */
const memoryExportRequests = (): ExportRequests & {
  seed(record: ExportRequestRecord): void;
  all(): readonly ExportRequestRecord[];
} => {
  const rows: ExportRequestRecord[] = [];
  let minted = 0;
  return {
    seed: (record) => {
      rows.push(record);
    },
    all: () => rows,
    request: async (input) => {
      minted += 1;
      const record: ExportRequestRecord = {
        export_id: `export-${String(minted)}`,
        org_id: input.org_id,
        requested_by_user_id: input.requested_by_user_id,
        requested_at: input.requested_at,
        state: "queued",
        bundle: null,
      };
      rows.push(record);
      return record;
    },
    get: async (org_id, export_id) =>
      rows.find((row) => row.org_id === org_id && row.export_id === export_id) ?? null,
    list: async (org_id) => rows.filter((row) => row.org_id === org_id),
  };
};

type Rpc = { status: number; body: Record<string, unknown> };
const QUERIES = new Set(["governance.exportStatus", "governance.exports"]);

type Host = {
  call(path: string, input: unknown, bearer?: string): Promise<Rpc>;
  login(email: string): Promise<string>;
  exports: ReturnType<typeof memoryExportRequests>;
};

const dataOf = (rpc: Rpc): unknown => {
  const result = (rpc.body as { result?: { data?: unknown } }).result;
  if (result === undefined) throw new Error(`expected a result, got ${JSON.stringify(rpc.body)}`);
  return superjson.deserialize(result.data as never);
};

const errorOf = (rpc: Rpc): { code?: string; message?: string } =>
  ((rpc.body as { error?: { json?: { message?: string; data?: { code?: string } } } }).error
    ?.json ?? {}) as { code?: string; message?: string };

const codeOf = (rpc: Rpc): string =>
  (
    rpc.body as { error?: { json?: { data?: { code?: string } } } }
  ).error?.json?.data?.code?.toString() ?? "";

let host: Host;
const token = new Map<string, string>();

const makeHost = async (): Promise<Host> => {
  const password_hash = await hashPin(PASSWORD);
  const users: UserRecord[] = [
    {
      user_id: A_OWNER,
      org_id: ORG_A,
      email: A_OWNER_EMAIL,
      display_name: "Ayesha Khan",
      password_hash,
      assignments: [{ role: "owner", branch_id: null }],
    },
    {
      user_id: A_MANAGER,
      org_id: ORG_A,
      email: A_MANAGER_EMAIL,
      display_name: "Hina Raza",
      password_hash,
      assignments: [{ role: "branch_manager", branch_id: A_BRANCH }],
    },
    {
      user_id: A_CASHIER,
      org_id: ORG_A,
      email: A_CASHIER_EMAIL,
      display_name: "Sana Iqbal",
      password_hash,
      assignments: [{ role: "cashier", branch_id: A_BRANCH }],
    },
    {
      user_id: B_OWNER,
      org_id: ORG_B,
      email: B_OWNER_EMAIL,
      display_name: "Bilal Ahmed",
      password_hash,
      assignments: [{ role: "owner", branch_id: null }],
    },
  ];

  const exports = memoryExportRequests();
  // One export already generated in EACH tenant, so both directions have something to leak and
  // something to control against. B's is the one every attack below reaches for.
  exports.seed({
    export_id: "export-a-existing",
    org_id: ORG_A,
    requested_by_user_id: A_OWNER,
    requested_at: T0 - 1000,
    state: "ready",
    bundle: A_BUNDLE,
  });
  exports.seed({
    export_id: "export-b-existing",
    org_id: ORG_B,
    requested_by_user_id: B_OWNER,
    requested_at: T0 - 2000,
    state: "ready",
    bundle: B_BUNDLE,
  });

  /**
   * ⚠ **Built as a VARIABLE and not as an object literal, on purpose.** TypeScript's excess
   * property check applies to a fresh literal in an argument position, so passing `exports`
   * inline would not compile until `ApiServerOptions` declares it — a repo-wide `pnpm typecheck`
   * failure, which is a broken build rather than a legitimate red (`24 §3`). Through a variable
   * the extra member is simply ignored by a host that has not learned about it yet, and the tests
   * below fail at RUNTIME with a message naming what is missing, which is the red an oracle owes.
   */
  const options = {
    store: createMemoryUserStore(users),
    sessionSecret: SECRET,
    now: () => T0,
    exports,
  };
  const app = await createApiServer(options);

  const call = async (path: string, input: unknown, bearer?: string): Promise<Rpc> => {
    const serialised = JSON.stringify(superjson.serialize(input));
    const auth: Record<string, string> =
      bearer === undefined ? {} : { authorization: `Bearer ${bearer}` };
    const res = QUERIES.has(path)
      ? await app.inject({
          method: "GET",
          url: `/trpc/${path}?input=${encodeURIComponent(serialised)}`,
          headers: auth,
        })
      : await app.inject({
          method: "POST",
          url: `/trpc/${path}`,
          headers: { "content-type": "application/json", ...auth },
          payload: serialised,
        });
    return { status: res.statusCode, body: JSON.parse(res.body) as Record<string, unknown> };
  };

  return {
    call,
    exports,
    login: async (email) => {
      const res = await call("auth.login", { email, password: PASSWORD });
      if (res.status !== 200) throw new Error(`login failed: ${JSON.stringify(res.body)}`);
      return (dataOf(res) as { token: string }).token;
    },
  };
};

/** Every string and number in a response body, flattened — for "does this contain B?" sweeps. */
const scalarsOf = (value: unknown, into: string[] = []): string[] => {
  if (value === null || value === undefined) return into;
  if (typeof value === "object") {
    for (const [key, nested] of Object.entries(value as Record<string, unknown>)) {
      into.push(key);
      scalarsOf(nested, into);
    }
    return into;
  }
  into.push(String(value));
  return into;
};

const B_MARKERS = [ORG_B, B_OWNER, B_BRANCH, B_BUNDLE, "export-b-existing", B_OWNER_EMAIL];

describe("22-F16 / R38: the owner triggers an export of HER OWN org, and of nothing else", () => {
  beforeAll(async () => {
    host = await makeHost();
    for (const [id, email] of [
      [A_OWNER, A_OWNER_EMAIL],
      [A_MANAGER, A_MANAGER_EMAIL],
      [A_CASHIER, A_CASHIER_EMAIL],
      [B_OWNER, B_OWNER_EMAIL],
    ] as const) {
      token.set(id, await host.login(email));
    }
  });

  // ══ §0 the fixture can express a foreign tenant ════════════════════════════════════════════

  describe("§0 the fixture", () => {
    it("both tenants hold a generated export, and their markers are disjoint", () => {
      const a = host.exports.all().filter((row) => row.org_id === ORG_A);
      const b = host.exports.all().filter((row) => row.org_id === ORG_B);
      expect(a.length).toBeGreaterThan(0);
      expect(b.length).toBeGreaterThan(0);
      for (const marker of B_MARKERS) {
        expect(
          JSON.stringify(a),
          `${marker} appears in tenant A's rows, so a leak of it would be undetectable`,
        ).not.toContain(marker);
      }
    });
  });

  // ══ §A the trigger exists and is owner-only ════════════════════════════════════════════════

  describe("§A 22-F16 'owner-triggered … owner-role only'", () => {
    it("A1 an owner can request an export of her own org", async () => {
      const rpc = await host.call("governance.requestExport", {}, token.get(A_OWNER));
      expect(
        rpc.status,
        "governance.requestExport is not reachable. R38 makes an owner-triggered export one of " +
          `three things that make R21's "real business records" honest: ${JSON.stringify(rpc.body)}`,
      ).toBe(200);
      const answer = dataOf(rpc) as { export_id?: string; state?: string };
      expect(String(answer.export_id ?? "")).not.toBe("");
      // `22-N3`: "owner sees progress state, never a spinner" — a state from a closed set is what
      // makes that renderable at all.
      expect(EXPORT_STATES).toContain(answer.state as ExportState);
    });

    it("A2 01-F71 (b): the request is recorded against the SUBJECT's org and the SUBJECT as actor", async () => {
      const rpc = await host.call("governance.requestExport", {}, token.get(A_OWNER));
      expect(rpc.status, JSON.stringify(rpc.body)).toBe(200);
      const { export_id } = dataOf(rpc) as { export_id: string };
      const stored = host.exports.all().find((row) => row.export_id === export_id);
      expect(stored?.org_id, "the export was recorded against the wrong org").toBe(ORG_A);
      expect(
        stored?.requested_by_user_id,
        "22-F16 requires the export to be audited, and the actor is the only part of that this " +
          "plane can supply today — governance.export_generated has no payload schema, so the " +
          "ledger record is owed (28-F14)",
      ).toBe(A_OWNER);
    });

    it("A3 a CASHIER is refused, as an authorization decision and not as a missing route", async () => {
      // THE CONTROL FIRST. A `refuses(...)` assertion against a procedure that does not exist
      // passes for free — this repo has measured 19 of 53 such assertions green against a codec
      // where the kind did not exist. So the owner's success is asserted in the same test.
      const allowed = await host.call("governance.requestExport", {}, token.get(A_OWNER));
      expect(allowed.status, `the control did not succeed: ${JSON.stringify(allowed.body)}`).toBe(
        200,
      );
      const refused = await host.call("governance.requestExport", {}, token.get(A_CASHIER));
      expect(refused.status).not.toBe(200);
      expect(
        codeOf(refused),
        `a cashier's export request was refused for the wrong reason: ${errorOf(refused).message}`,
      ).toBe("FORBIDDEN");
    });

    it("A4 22-F16 'owner-role ONLY': a branch manager is refused too", async () => {
      const allowed = await host.call("governance.requestExport", {}, token.get(A_OWNER));
      expect(allowed.status).toBe(200);
      const refused = await host.call("governance.requestExport", {}, token.get(A_MANAGER));
      expect(
        codeOf(refused),
        "22-F16 says owner-role only. 22 §7 makes WHO may trigger it a layer-2 setting with an " +
          "owner default, and no layer-2 plane exists — so the default is the rule today.",
      ).toBe("FORBIDDEN");
    });

    it("A5 an unauthenticated caller reaches nothing", async () => {
      // Anchored, for the reason §A3 states: without the control this passes against a route that
      // does not exist, which is a claim about nothing.
      const allowed = await host.call("governance.requestExport", {}, token.get(A_OWNER));
      expect(allowed.status, `the control did not succeed: ${JSON.stringify(allowed.body)}`).toBe(
        200,
      );
      const rpc = await host.call("governance.requestExport", {});
      expect(rpc.status).not.toBe(200);
      expect(codeOf(rpc)).toBe("UNAUTHORIZED");
    });
  });

  // ══ §B two tenants ═════════════════════════════════════════════════════════════════════════

  describe("§B 01-F71: 'a subject authenticated in one org must never read … data belonging to another'", () => {
    it("B1 tenant A cannot read tenant B's export by its id — and B's own owner can", async () => {
      // The control, in the same test and against the same host: the record is genuinely there
      // and genuinely reachable by the tenant entitled to it. Without it, "A got nothing" is
      // indistinguishable from "the procedure is broken for everybody".
      const mine = await host.call(
        "governance.exportStatus",
        { export_id: "export-b-existing" },
        token.get(B_OWNER),
      );
      expect(
        mine.status,
        `B's own owner could not read B's export: ${JSON.stringify(mine.body)}`,
      ).toBe(200);
      expect(JSON.stringify(dataOf(mine))).toContain(B_BUNDLE);

      const theirs = await host.call(
        "governance.exportStatus",
        { export_id: "export-b-existing" },
        token.get(A_OWNER),
      );
      const leaked = theirs.status === 200 ? JSON.stringify(dataOf(theirs)) : "";
      expect(
        leaked,
        "tenant A read tenant B's export record. An export id is a CAPABILITY — it names a bundle " +
          "holding another restaurant's complete ledger — so a lookup by id with no org predicate " +
          "is the whole leak in one query (01-F71).",
      ).not.toContain(B_BUNDLE);
    });

    it("B2 an org stated by the CALLER changes nothing — 01-F71 (b)", async () => {
      const rpc = await host.call(
        "governance.requestExport",
        // Not part of the pinned input. A correct implementation ignores or rejects it; what it
        // must never do is believe it. `28-F5` (b): "There is no tenant-context header, no ?org=
        // on a tenant API and no impersonation shortcut through one."
        { org_id: ORG_B, branch_id: B_BRANCH },
        token.get(A_OWNER),
      );
      if (rpc.status === 200) {
        const { export_id } = dataOf(rpc) as { export_id: string };
        const stored = host.exports.all().find((row) => row.export_id === export_id);
        expect(
          stored?.org_id,
          "tenant A asked for an export and named tenant B in the request, and the request was " +
            "recorded against tenant B. The org comes from the authenticated subject and never " +
            "from the request (01-F71 (b)).",
        ).toBe(ORG_A);
      } else {
        // Refusing the unknown field outright is also correct — but only if the same call
        // without it succeeds, which §A1 asserts.
        expect(codeOf(rpc)).toBe("BAD_REQUEST");
      }
      // And nothing was minted under B by any route.
      expect(
        host.exports.all().filter((row) => row.org_id === ORG_B).length,
        "a request made by tenant A created a row under tenant B",
      ).toBe(1);
    });

    it("B3 nothing tenant A can see through this surface mentions tenant B", async () => {
      const requested = await host.call("governance.requestExport", {}, token.get(A_OWNER));
      expect(requested.status).toBe(200);
      const { export_id } = dataOf(requested) as { export_id: string };
      const status = await host.call("governance.exportStatus", { export_id }, token.get(A_OWNER));
      expect(status.status, JSON.stringify(status.body)).toBe(200);
      const seen = scalarsOf(dataOf(status));
      // The control: A's own answer really does carry A's identifiers, so this sweep is looking
      // at something.
      expect(seen.join(" "), "A's own export record does not name A").toContain(ORG_A);
      for (const marker of B_MARKERS) {
        expect(seen.join(" "), `tenant B's ${marker} reached tenant A`).not.toContain(marker);
      }
    });
  });
});
